name: Publish to NPM

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
     id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
        
      - name: Generate Prisma client
        run: pnpx prisma@5.22.0 generate
        
      - name: Build package
        run: pnpm package
        
# Additional step to extract version from the release tag
      - name: Extract version from tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
         TAG_VERSION=${GITHUB_REF#refs/tags/v}
         pnpm version $TAG_VERSION --no-git-tag-version
         echo "Setting package version to $TAG_VERSION"
        
      - name: Publish to NPM
        run: pnpm publish --no-git-checks --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
